resources:
- namespace.yaml
- service-account.yaml
helmCharts:
- name: gitops-operator
  includeCRDs: false
  valuesInline:
    ignoreHelmHooks: true
    operator: []
    namespaces:
    - fteam-ci-cd
    argocd_cr:
      repositoryCredentials: |
        - url: gitlab-ce.apps.sno.sandbox1131.opentlc.com
          type: git
          passwordSecret:
            key: password
            name: git-auth
          usernameSecret:
            key: username
            name: git-auth
  releaseName: argocd
  version: 0.9.3
  repo: https://redhat-cop.github.io/helm-charts